-- MySQL Script generated by MySQL Workbench
-- Mon Jan 15 19:26:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet_dbpy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projet_dbpy` ;

-- -----------------------------------------------------
-- Schema projet_dbpy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet_dbpy` DEFAULT CHARACTER SET utf8 ;
USE `projet_dbpy` ;

-- -----------------------------------------------------
-- Table `projet_dbpy`.`exercices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_dbpy`.`exercices` ;

CREATE TABLE IF NOT EXISTS `projet_dbpy`.`exercices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = INNODB;

/*Data for the table `exercices` */
INSERT INTO `exercices` (`NAME`) VALUES
('GEO01'),
('INFO02'),
('INFO05');


-- -----------------------------------------------------
-- Table `projet_dbpy`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_dbpy`.`users` ;

CREATE TABLE IF NOT EXISTS `projet_dbpy`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `level` TINYINT NOT NULL,
  `salt` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_dbpy`.`results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_dbpy`.`results` ;

CREATE TABLE IF NOT EXISTS `projet_dbpy`.`results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(40) NOT NULL,
  `start_date_hour` DATETIME NOT NULL,
  `duration` TIME NOT NULL,
  `nb_ok` INT NOT NULL,
  `nb_total` INT NOT NULL,
  `exercice_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `fk_students_has_exercices_exercices1_idx` (`exercice_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_results_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_exercices_exercices1`
    FOREIGN KEY (`exercice_id`)
    REFERENCES `projet_dbpy`.`exercices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projet_dbpy`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
